// components/pdf-analysis-display.tsx

type AnalysisData = {
  file: {
    originalName: string;
    uploadedAt: string;
  };
  analysis: {
    transcript: string;
    response: string;
  };
};

export default function PDFAnalysisDisplay({ data }: { data: AnalysisData }) {
  const uploadedDate = new Date(data.file.uploadedAt).toLocaleString("en-IN", {
    dateStyle: "long",
    timeStyle: "short",
  });

  const {
    transcript,
    response, // This is a pre-formatted markdown-style string
  } = data.analysis;

  return (
    <div className="min-h-screen bg-white text-black px-12 py-10 font-sans">
      {/* Header */}
      <header className="border-b border-gray-300 pb-4 mb-6">
        <h1 className="text-3xl font-bold text-blue-800">SonicScribe Health Analysis Report</h1>
        <p className="text-sm text-gray-500">Audio: {data.file.originalName}</p>
        <p className="text-sm text-gray-500">Uploaded: {uploadedDate}</p>
      </header>

      {/* Section: Transcript */}
      <section className="mb-6">
        <h2 className="text-xl font-semibold text-gray-800 mb-2 border-b">🗣️ Patient Voice Transcript</h2>
        <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{transcript}</p>
      </section>

      {/* Section: Extracted Analysis */}
      <section className="mb-6">
        <h2 className="text-xl font-semibold text-gray-800 mb-2 border-b">📝 AI-Generated Medical Analysis</h2>
        <div className="text-gray-700 whitespace-pre-wrap leading-relaxed">
          {response}
        </div>
      </section>

      {/* Optional: Footer */}
      <footer className="text-center text-sm text-gray-400 border-t pt-6 mt-6">
        <p>Generated by SonicScribe AI — Empowering Early Diagnostics</p>
        <p>© {new Date().getFullYear()} SonicScribe</p>
      </footer>
    </div>
  );
}
